pe_unit_test:../PixelEngine.cpp unit-test.cpp
	g++ -I../ -I../v8include -I./  unit-test.cpp ../lodepng.cpp ../PixelEngine.cpp  ../PeTileData.cpp ../PeStyle.cpp ../PeProductInfo.cpp ../wAST.cpp ../OfflineTask.cpp ../wTextfilereader.cpp ../wstringutil.cpp ../peroi.cpp ../pemultipolygon.cpp -o pe_unit_test -fPIC -lv8_monolith -L../v8lib -lpthread -ldl -std=c++0x -O2  
