/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pixelengine_HBasePeHelperCppConnector */

#ifndef _Included_com_pixelengine_HBasePeHelperCppConnector
#define _Included_com_pixelengine_HBasePeHelperCppConnector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pixelengine_HBasePeHelperCppConnector
 * Method:    ParseScriptForDsDt
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_pixelengine_HBasePeHelperCppConnector_ParseScriptForDsDt
  (JNIEnv *, jobject, jstring, jstring);


/* 2022-2-12 获取脚本中全部数据集名称,返回结果是Json格式字符串{status:0,error:"",data:[...]}
 * Class:     com_pixelengine_HBasePeHelperCppConnector
 * Method:    GetDatasetNameArray
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_pixelengine_HBasePeHelperCppConnector_GetDatasetNameArray
  (JNIEnv *, jobject, jstring, jstring);



/*
 * Class:     com_pixelengine_HBasePeHelperCppConnector
 * Method:    RunScriptForTileWithoutRender
 * Signature: (Ljava/lang/String;Ljava/lang/String;JIII)Lcom/pixelengine/TileComputeResult;
 */
JNIEXPORT jobject JNICALL Java_com_pixelengine_HBasePeHelperCppConnector_RunScriptForTileWithoutRender
  (JNIEnv *, jobject, jstring, jstring, jlong, jint, jint, jint);

/*
 * Class:     com_pixelengine_HBasePeHelperCppConnector
 * Method:    RunScriptForTileWithRender
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;JIII)Lcom/pixelengine/TileComputeResult;
 */
JNIEXPORT jobject JNICALL Java_com_pixelengine_HBasePeHelperCppConnector_RunScriptForTileWithRender
  (JNIEnv *, jobject, jstring, jstring, jstring, jlong, jint, jint, jint);

/*
 * Class:     com_pixelengine_HBasePeHelperCppConnector
 * Method:    RunScriptForTileWithoutRenderWithExtra
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;III)Lcom/pixelengine/TileComputeResult;
 */
JNIEXPORT jobject JNICALL Java_com_pixelengine_HBasePeHelperCppConnector_RunScriptForTileWithoutRenderWithExtra
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jint, jint);



/* 2022-9-7
 * Class:     com_pixelengine_HBasePeHelperCppConnector
 * Method:    RunScriptFunctionForTileResult
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;III)Lcom/pixelengine/TileComputeResult;
 */
JNIEXPORT jobject JNICALL Java_com_pixelengine_HBasePeHelperCppConnector_RunScriptFunctionForTileResult
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jint, jint);

/* 2022-9-9
 * Class:     com_pixelengine_HBasePeHelperCppConnector
 * Method:    RunScriptFunctionForTextResultOrNothing
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;III)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_pixelengine_HBasePeHelperCppConnector_RunScriptFunctionForTextResultOrNothing
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jint, jint);




/* 2022-3-22 增加返回dsname,dt roi2 和 log信息到 TileComputeResultWithRunAfterInfo 里面
 * Class:     com_pixelengine_HBasePeHelperCppConnector
 * Method:    RunScriptForTileWithoutRenderWithExtraWithRunAfterInfo
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;III)Lcom/pixelengine/TileComputeResultWithRunAfterInfo;
 */
JNIEXPORT jobject JNICALL Java_com_pixelengine_HBasePeHelperCppConnector_RunScriptForTileWithoutRenderWithExtraWithRunAfterInfo
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jint, jint);







/*
 * Class:     com_pixelengine_HBasePeHelperCppConnector
 * Method:    RunScriptForTileWithRenderWithExtra
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;III)Lcom/pixelengine/TileComputeResult;
 */
JNIEXPORT jobject JNICALL Java_com_pixelengine_HBasePeHelperCppConnector_RunScriptForTileWithRenderWithExtra
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jint, jint, jint);

/*
 * Class:     com_pixelengine_HBasePeHelperCppConnector
 * Method:    CheckScriptOk
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_pixelengine_HBasePeHelperCppConnector_CheckScriptOk
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_pixelengine_HBasePeHelperCppConnector
 * Method:    GetVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_pixelengine_HBasePeHelperCppConnector_GetVersion
  (JNIEnv *, jobject);

/*
 * Class:     com_pixelengine_HBasePeHelperCppConnector
 * Method:    RunToGetStyleFromScript
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_pixelengine_HBasePeHelperCppConnector_RunToGetStyleFromScript
  (JNIEnv *, jobject, jstring, jstring);


/* 2022-3-23 工具方法计算hsegtlv 的level0 的四至范围，注意该范围可能略小于实际范围，可以通过向外推一个像素即可肯定完全包括。
 * 成功返回四至范围数字组成的字符串，由逗号分割，顺序如后 left,right,top,bottom
 * 失败返回空字符串
 * Class:     com_pixelengine_HBasePeHelperCppConnector
 * Method:    UtilsComputeHsegTlvExtent
 * Signature: ([B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_pixelengine_HBasePeHelperCppConnector_UtilsComputeHsegTlvExtent
  (JNIEnv *, jobject, jbyteArray);


/* 2022-3-23 TileComputeResult 直接使用hseg.tlv裁剪接口，不经过V8和js代码
 * Class:     com_pixelengine_HBasePeHelperCppConnector
 * Method:    ClipTileComputeResultByHsegTlv
 * Signature: (Lcom/pixelengine/TileComputeResult;[BD)Lcom/pixelengine/TileComputeResult;
 */
JNIEXPORT jobject JNICALL Java_com_pixelengine_HBasePeHelperCppConnector_ClipTileComputeResultByHsegTlv
  (JNIEnv *, jobject, jstring , jobject, jbyteArray, jdouble filldata);


/* 2022-3-26 直接对瓦片结果进行统计，不用v8
 * Class:     com_pixelengine_HBasePeHelperCppConnector
 * Method:    ComputeStatisticTileComputeResultByHsegTlv
 * Signature: (Ljava/lang/String;Lcom/pixelengine/TileComputeResult;[BDDD)Lcom/pixelengine/JStatisticData;
 */
JNIEXPORT jobject JNICALL Java_com_pixelengine_HBasePeHelperCppConnector_ComputeStatisticTileComputeResultByHsegTlv
  (JNIEnv *env, jobject obj, jstring clsname, jobject tcr, jbyteArray hsegtlvdata, jdouble filldata, jdouble vMinInc,jdouble vMaxInc);


/* 2022-7-17 计算main函数的文本结果，基于pe的代码，需要v8
 * Class:     com_pixelengine_HBasePeHelperCppConnector
 * Method:    RunScriptForTextResultWithExtra
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_pixelengine_HBasePeHelperCppConnector_RunScriptForTextResultWithExtra
  (JNIEnv *, jobject, jstring, jstring, jstring);


/* 2022-9-27 裁剪二进制瓦片数据，裁剪区外使用filldata填充，不用v8，如果失败返回0字节数组
 * Class:     com_pixelengine_HBasePeHelperCppConnector
 * Method:    ClipBinaryTileData
 * Signature: ([BIIIIIII[BD)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_pixelengine_HBasePeHelperCppConnector_ClipBinaryTileData
  (JNIEnv *env, jobject obj, jstring clsname,
    jbyteArray dataArr,jint datatype,
    jint width,jint height,jint nbands,
    jint z,jint y,jint x,
    jbyteArray tlvdata,jdouble filldata);

/* 2022-9-27 数据使用PeStyle（JSON格式字符串，可以为空PeStyle，空Style使用0-255渲染）渲染RGBA byte 4波段数组，不用v8，如果失败返回0字节数组
 * Class:     com_pixelengine_HBasePeHelperCppConnector
 * Method:    RenderTileData2Rgba
 * Signature: ([BIIIILjava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_pixelengine_HBasePeHelperCppConnector_RenderTileData2Rgba
  (JNIEnv *env, jobject obj, jstring clsname,
    jbyteArray dataArr,jint datatype,
    jint width,jint height,jint nbands,
    jstring peStyleJsonText);

/* 2022-9-27 4波段RGBA byte数组转压缩png二进制数据，不用v8，如果失败返回0字节数组
 * Class:     com_pixelengine_HBasePeHelperCppConnector
 * Method:    ConvertRgbaData2PngBinary
 * Signature: ([BII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_pixelengine_HBasePeHelperCppConnector_ConvertRgbaData2PngBinary
  (JNIEnv *env, jobject obj, jstring clsname,
    jbyteArray rgbaData,
    jint width,jint height );



#ifdef __cplusplus
}
#endif
#endif
