/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Demo */

#ifndef _Included_Demo
#define _Included_Demo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Demo
 * Method:    CallTileCompute
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_Demo_CallTileCompute
  (JNIEnv *, jobject);

/*
 * Class:     Demo
 * Method:    Version
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Demo_Version
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
