/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pixelengine_V8Helper */

#ifndef _Included_com_pixelengine_V8Helper
#define _Included_com_pixelengine_V8Helper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pixelengine_V8Helper
 * Method:    CallTileCompute
 * Signature: (Ljava/lang/String;IIII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_pixelengine_V8Helper_CallTileCompute
  (JNIEnv *, jobject, jstring, jlong, jint, jint, jint);

/*
 * Class:     com_pixelengine_V8Helper
 * Method:    Version
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_pixelengine_V8Helper_Version
  (JNIEnv *, jobject);

/*
 * Class:     com_pixelengine_V8Helper
 * Method:    CheckScriptOK
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_pixelengine_V8Helper_CheckScriptOK
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_pixelengine_V8Helper
 * Method:    ComputeOnce
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_pixelengine_V8Helper_ComputeOnce
  (JNIEnv *, jobject, jstring);


/*
 * Class:     com_pixelengine_V8Helper
 * Method:    CallTileComputeV2
 * Signature: (Ljava/lang/String;JIII)Lcom/pixelengine/V8HelperResult;
 */
JNIEXPORT jobject JNICALL Java_com_pixelengine_V8Helper_CallTileComputeV2
  (JNIEnv *, jobject, jstring, jlong, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
