/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pixelengine_V8Helper */

#ifndef _Included_com_pixelengine_V8Helper
#define _Included_com_pixelengine_V8Helper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pixelengine_V8Helper
 * Method:    CallTileCompute
 * Signature: (Ljava/lang/String;IIII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_pixelengine_V8Helper_CallTileCompute
  (JNIEnv *, jobject, jstring, jint, jint, jint, jint);

/*
 * Class:     com_pixelengine_V8Helper
 * Method:    Version
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_pixelengine_V8Helper_Version
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
