/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pixelengine_CppZonalStat */

#ifndef _Included_com_pixelengine_CppZonalStat
#define _Included_com_pixelengine_CppZonalStat
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pixelengine_CppZonalStat
 * Method:    doit
 * Signature: ([I[BIIDDDIII)Lcom/pixelengine/ZonalStatResult;
 */
JNIEXPORT jobject JNICALL Java_com_pixelengine_CppZonalStat_doit
  (JNIEnv *, jobject, jintArray, jbyteArray, jint, jint, jdouble, jdouble, jdouble, jint, jint, jint);

/*
 * Class:     com_pixelengine_CppZonalStat
 * Method:    assignDataBytes
 * Signature: ([BDDI[B[S)V
 */
JNIEXPORT void JNICALL Java_com_pixelengine_CppZonalStat_assignDataBytes
  (JNIEnv *, jobject, jbyteArray, jdouble, jdouble, jint, jbyteArray, jshortArray);

/*
 * Class:     com_pixelengine_CppZonalStat
 * Method:    combineDataBytes
 * Signature: ([BDDII[B[S)V
 */
JNIEXPORT void JNICALL Java_com_pixelengine_CppZonalStat_combineDataBytes
  (JNIEnv *, jobject, jbyteArray, jdouble, jdouble, jint, jint, jbyteArray, jshortArray);

#ifdef __cplusplus
}
#endif
#endif
