TileComputeV8Helper:../PixelEngine.cpp ../TileComputeV8Helper.cpp
	g++ -shared -I../ -I../v8include -I./ -I/usr/local/jdk1.8.0_192/include -I/usr/local/jdk1.8.0_192/include/linux ../lodepng.cpp ../TileComputeV8Helper.cpp ../PixelEngine.cpp -o libTileComputeV8Helper.so -fPIC -lv8_monolith -L../v8lib -lpthread -ldl -std=c++0x -O2 
